#!/bin/sh
set -euo pipefail

read -p "Enter your AUTH_DISCORD_ID: " AUTH_DISCORD_ID
read -p "Enter your AUTH_DISCORD_SECRET: " AUTH_DISCORD_SECRET
read -p "Enter your SUNOAPI_API_KEY: " SUNOAPI_API_KEY
read -p "Enter your PROXY_URL: " PROXY_URL

POSTGRES_PASSWORD=$(openssl rand -hex 32)
MINIO_PASSWORD=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)

cat << EOF
HOSTNAME=0.0.0.0
PORT=8080
POSTGRES_URL=postgres://postgres:$POSTGRES_PASSWORD@localhost:5432/postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=postgres
MINIO_USER=minioadmin
MINIO_PASSWORD=$MINIO_PASSWORD
MINIO_ENDPOINT=localhost
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_BUCKET_NAME_MUSIC=music
MINIO_BUCKET_NAME_ARTIST_IMAGES=artist-images
MINIO_BUCKET_NAME_ALBUM_IMAGES=album-images
MINIO_BUCKET_NAME_PLAYLIST_IMAGES=playlist-images
AUTH_SECRET=$NEXTAUTH_SECRET
AUTH_URL=http://localhost:3000
AUTH_TRUST_HOST=true
AUTH_DISCORD_ID=$AUTH_DISCORD_ID
AUTH_DISCORD_SECRET=$AUTH_DISCORD_SECRET
NEXT_PUBLIC_IS_STAGING=true
SUNOAPI_API_KEY=$SUNOAPI_API_KEY
NEXT_PUBLIC_MINIO_URL=http://localhost:9000
EOF