#!/bin/sh
set -euo pipefail

read -p "Enter your Discord client ID: " DISCORD_CLIENT_ID
read -p "Enter your Discord client secret: " DISCORD_CLIENT_SECRET

POSTGRES_PASSWORD=$(openssl rand -hex 32)
MINIO_PASSWORD=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)

cat << EOF
POSTGRES_URL=postgres://postgres:$POSTGRES_PASSWORD@localhost:5432/postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=postgres
MINIO_USER=minioadmin
MINIO_PASSWORD=$MINIO_PASSWORD
MINIO_ENDPOINT=localhost
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_BUCKET_NAME_MUSIC=music
MINIO_BUCKET_NAME_ARTIST_IMAGES=artist-images
MINIO_BUCKET_NAME_ALBUM_IMAGES=album-images
MINIO_BUCKET_NAME_PLAYLIST_IMAGES=playlist-images
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
NEXTAUTH_URL=http://localhost:3000
DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
NEXT_PUBLIC_IS_STAGING=true
EOF